apiVersion: v1
kind: Service
metadata:
  name: php-apache-svc
  namespace: hpa-demo
spec:
  selector:
    app: php-apache
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
